#!/bin/bash

if [ -z "$2" ]; then		# if no pattern or repository is passed
  	echo "Usage: file_search <repo> <pattern>"
	exit
fi

repo=$1

if [ ! -d "$repo" ]; then		# if the directory in which to search does not exist
	echo "Directory \"$repo\" does not exist."
	exit
fi

find_output=`find $repo -type f`		# holds the names of all files in the working directory
if [ -n "$find_output" ]; then		# if at least one file has been found
	while read file_name; do
		if [ -n "`grep -i "$2" "$file_name"`" ]; then		# if this file contains the pattern (case insensitive)
			file_list+="./`echo $file_name | cut -d/ -f2-`\n"
		fi
	done <<< "$find_output"		# $find_output is redirected to the stdin of the loop's read command
fi

if [ -z "$file_list" ]; then		# if the list of files containing the pattern is empty
	echo "Pattern not found."
else
	echo -e "$file_list" | sort	# prints the sorted list of files containing the pattern
	echo ""
fi
