#!/bin/bash

if [ -z "$2" ]; then
  	echo "Usage: file_search <repo> <pattern>"
	exit
fi

repo=$1

if [ ! -d "$1" ]; then
	echo "Directory \"$repo\" does not exist."
	exit
fi

find_output=`find $repo -type f`
while read file_name; do
	if [ -n "`grep "$2" "$file_name"`" ]
		file_list+="$file_name\n"
done <<< "$find_output"

# Ordinare e formattare la lista (file_list)
