#!/bin/bash

function create_dir {
	if [ -d "$1" ]; then		# if the directory already exists
		echo "Directory \"$1\" already exists."	# there's nothing to do
	else
		mkdir "$1"		# otherwise, it creates the directory
		if [ $? -eq 0 ]; then	# if the exit code of mkdir is equal to 0
			echo "Directory \"$1\" has been successfully created."
		fi
	fi
}

if [ -n "$2" ] || [ -z "$1" ]; then		# if more than 1 argument is passed
	echo "Usage: init_repo <repo>"	
	exit			
fi

create_dir ".$1.bck"		# calls create-dir to create the backup directory
create_dir "$1"			# calls create-dir to create the working directory
