#!/bin/bash

function init_repo {
	./init_repo $repo "$args"
}

function commit {
	./commit $repo "$args"
}

function remove {
	./remove $repo "$args"
}

function revert {
	./revert $repo "$args"
}

function status {
	./status $repo "$args"
}

function file_search {
	./file_search $repo "$args"
}


echo -e "\n\t1 - init_repo\n\t2 - commit\n\t3 - remove\n\t4 - revert\n\t5 - status\n\t6 - file_search\n\t7 - quit\n"
while [ true ]; do				
	read -p "(myversioning) " cmd		# reads a command with a prompt string
	repo=`echo $cmd | cut -d" " -s -f2`	# the second field of cmd is the name of repository
	args=`echo $cmd | cut -d" " -s -f3-`	# arguments of the command start from the third field until the end of the string
	cmd=`echo $cmd | cut -d" " -f1`		# the first field of cmd is the function requested
	case $cmd in				# switches on cmd calling the corresponding script
		"init_repo") init_repo;;
		"commit") commit;;
		"remove") remove;;
		"revert") revert;;
		"status") status;;
		"file_search") file_search;;
		"quit") exit 0;;
		*) echo "Unknown command: \"$cmd\".";;
	esac
done
