#!/bin/bash

function init_repo {
	./init_repo $args
}

function commit {
	./commit $args
}

function remove {
	./remove $args
}

function revert {
	./revert $args
}

function status {
	./status $args
}

function file_search {
	./file_search $args
}

echo -e "\n\t1 - init_repo\n\t2 - commit\n\t3 - remove\n\t4 - revert\n\t5 - status\n\t6 - file_search\n\t7 - quit\n"
while [ true ]; do
	read -p "(myversioning) " cmd
	args=`echo $cmd | cut -d" " -s -f2-`
	cmd=`echo $cmd | cut -d" " -f1`
	case $cmd in
		"init_repo") init_repo;;
		"commit") commit;;
		"remove") remove;;
		"revert") revert;;
		"status") status;;
		"file_search") file_search;;
		"quit") exit 0;;
		*) echo "Unknown command: \"$cmd\".";;
	esac
done
