#!/bin/bash

function remove_file {
	if [ -f "$1" ]; then
		rm -f "$1"  #-f per forzare rimozione
		if [ $? -eq 0 ]; then
			echo "$2 copy of file has been successfully removed."
		fi
	else
		echo "$2 copy of file does not exist."
	fi

}


if [ -z "$2" ]; then
  	echo "Usage: remove <repo> <file name>"
	exit
fi

backup_dir=".$1.bck"
working_copy="$1/$2"
backup_copy="$backup_dir/$2"

if [ ! -d "$backup_dir" ]; then
	echo "Repository \"$1\" does not exist."
	exit
fi

remove_file "$working_copy" "Working"
remove_file "$backup_copy" "Backup"
