#!/bin/bash

if [ -z "$2" ]; then
  	echo "Usage: remove <repo> <file name>"
	exit
fi

backup_dir=".$1.bck"
working_copy="$1/$2"
backup_copy="$backup_dir/$2"

if [ ! -d "$backup_dir" ]; then
	echo "Repository \"$1\" does not exist."
	exit
fi

if [ -f "$backup_copy" ]; then
	rm -f "$backup_copy"  #-f per forzare rimozione
	if [ $? -eq 0 ]; then
		echo "Backup copy of file \"$2\" has been successfully removed."
	fi
else
	echo "Backup copy of file \"$2\" does not exist."
fi

if [ -f "$working_copy" ]; then
	rm -f "$working_copy"  #-f per forzare rimozione
	if [ $? -eq 0 ]; then
		echo "Working copy of file \"$2\" has been successfully removed."
	fi
	
else
	echo "Working copy of file \"$2\" does not exist."
fi
