#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: status <repo>"
	exit 1;
fi

working_dir=$1
backup_dir=".$1.bck"

if [ ! -d "$working_dir" ]; then 
	echo "Directory \"$working_dir\" does not exist."
	exit 1;
fi

if [ ! -d "$backup_dir" ]; then
	echo "Repository \"$1\" has not been initialized."
	exit 1;
fi

for file in `find $working_dir -type f`; do
	file_backup="$backup_dir/`echo $file | cut -d/ -f2-`"  #taglia via il $working_dir/
	if [ ! -f "$file_backup" ] || [ -n "`diff $file $file_backup`" ]; then
		echo $file | cut -d/ -f2-
	fi
done
